components:
  menu_bar: true
  toolbar: true
  tray_bar: true
  content_area: true
toolbar:
  - g-open-session
  - g-save-session
  - g-import-data
  - g-export-data
  - spacer
  - vertical-divider
  - g-active-subset
  - vertical-divider
  - spacer
  - g-selection-state
menu_bar:
  - g-test-action
tray_bar:
  - g-data-collection-list
  - g-viewer-options
  - g-layer-options
content_area:
  - top_area:
      - g-imshow
  - bottom_area:
      - g-profile-1d
