settings:
  visible:
    menu_bar: false
    toolbar: true
    tray: true
    tab_headers: true
toolbar:
  - g-data-tools
  - g-viewer-creator
  - g-subset-tools
  - g-gaussian-smooth
tray:
  - g-model-fitting
