components:
  menu_bar: true
  toolbar: true
  interact_drawer: true
  content_area: true
toolbar:
  - g-open-session
  - g-save-session
  - g-import-data
  - g-export-data
  - spacer
  - g-active-subset
  - spacer
  - g-selection-state
menu_bar:
  - g-test-action
