settings:
  configuration: mosviz
  visible:
    menu_bar: false
    toolbar: true
    tray: true
    tab_headers: true
  context:
    notebook:
      max_height: 600px
toolbar:
  - g-data-tools
  - g-subset-tools
  - g-unified-slider
tray:
  - g-gaussian-smooth
  - g-collapse
viewer_area:
  - container: stack
    children:
    - container: row
      children:
      - container: row
        viewers:
          - name: Image viewer
            plot: mosviz-image-viewer
            reference: image-viewer
      - container: col
        viewers:
          - name: 2D Spectrum viewer
            plot: mosviz-image-viewer
            reference: spectrum-2d-viewer
          - name: Spectrum
            plot: mosviz-profile-viewer
            reference: spectrum-viewer
#    - container: col
#      children:
#      - container: row
#        viewers:
#        - name: Image viewer
#          plot: mosviz-table-viewer
#          reference: table-viewer
