settings:
  configuration: mosviz
  visible:
    menu_bar: false
    toolbar: true
    tray: true
    tab_headers: false
  context:
    notebook:
      max_height: 600px
toolbar:
  - g-data-tools
  - g-subset-tools
  - g-unified-slider
tray:
  - g-gaussian-smooth
  - g-collapse
viewer_area:
  - container: col
    children:
      - container: row
        viewers:
          - name: Image viewer
            plot: mosviz-image-viewer
            reference: mos-image-viewer
          - name: 2D Spectrum viewer
            plot: mosviz-image-viewer
            reference: mos-2d-spectrum-viewer
      - container: row
        viewers:
          - name: Spectrum
            plot: mosviz-profile-viewer
            reference: spectrum-viewer
