settings:
  configuration: cubeviz
  visible:
    menu_bar: false
    toolbar: true
    tray: true
    tab_headers: false
toolbar:
  - g-data-tools
  - g-viewer-creator
  - g-subset-tools
  - g-gaussian-smooth
viewer_area:
  - container: col
    children:
      - container: row
        viewers:
          - name: Flux
            plot: g-image-viewer
          - name: Uncertainty
            plot: g-image-viewer
          - name: Mask
            plot: g-image-viewer
      - container: row
        viewers:
          - name: Spectrum
            plot: g-profile-viewer
