settings:
  configuration: cubeviz
  visible:
    menu_bar: false
    toolbar: true
    tray: true
    tab_headers: false
toolbar:
  - g-data-tools
  - g-viewer-creator
  - g-subset-tools
  - g-gaussian-smooth
