settings:
  configuration: cubeviz
  visible:
    menu_bar: false
    toolbar: true
    tray: true
    tab_headers: false
toolbar:
  - g-data-tools
  - g-subset-tools
  - g-gaussian-smooth
  - g-collapse
  - g-unified-slider
viewer_area:
  - container: col
    children:
      - container: row
        viewers:
          - name: Flux
            plot: g-cubeviz-image-viewer
            reference: flux-viewer
          - name: Uncertainty
            plot: g-cubeviz-image-viewer
            reference: uncert-viewer
          - name: Mask
            plot: g-cubeviz-image-viewer
            reference: mask-viewer
      - container: row
        viewers:
          - name: Spectrum
            plot: g-profile-viewer
            reference: spectrum-viewer
