settings:
  configuration: specviz
  data:
    parser: specviz-spectrum1d-parser
  visible:
    menu_bar: false
    toolbar: true
    tray: true
    tab_headers: false
  context:
    notebook:
      max_height: 600px
toolbar:
  - g-data-tools
  - g-subset-tools
tray:
<<<<<<< HEAD
  - g-gaussian-smooth
  - g-model-fitting
  - specviz-line-analysis
  - g-unit-conversion
  - g-line-list
  - specviz-line-analysis
>>>>>>> Add line analysis plugin to specviz config
viewer_area:
  - container: col
    children:
      - container: row
        viewers:
          - name: Spectrum
            plot: specviz-profile-viewer
            reference: spectrum-viewer
