settings:
  configuration: specviz
  visible:
    menu_bar: false
    toolbar: true
    tray: true
    tab_headers: false
  context:
    notebook:
      max_height: 600px
toolbar:
  - g-data-tools
  - g-subset-tools
viewer_area:
  - container: col
    children:
      - container: row
        viewers:
          - name: Spectrum
            plot: specviz-profile-viewer
            reference: spectrum-viewer
